### ISSUE TITLE
Unable to observe unbound statistics

### ISSUE THREAD

**Issue by tckb** [svartalf/unbound-telemetry#4]
First of all, this is by far the best telemetry data I have seen for unbound.

Unfortunately, while trying to fetch the metrics and health-check, gives me the following error. 
`Unable to observe unbound statistics: failed to lookup address information: Name does not resolve`

The control server seems to be available and reachable. Any ideas on how to resolve this?

**Comment by svartalf** [comment]
Hey, @tckb and thank you!

At the end DNS resolving for a TCP address is done with libc `getaddrinfo` and `getnameinfo` functions, so it is up to your system resolver to do that (assuming that we are talking about *nix systems here); full chain for a reference:

1. https://github.com/tokio-rs/tokio/blob/master/tokio/src/net/addr.rs#L144-L149
2. https://github.com/rust-lang/rust/blob/c6b172f7885cb83842fa15e4b0e2ff1647aebb40/src/libstd/net/addr.rs#L894
3. https://github.com/rust-lang/rust/blob/c6b172f7885cb83842fa15e4b0e2ff1647aebb40/src/libstd/net/addr.rs#L867-L876
4. https://github.com/rust-lang/rust/blob/5e8897b7b51636f157630e6639b711d698e1d101/src/libstd/sys_common/net.rs#L186-L201

I would probably start by checking if that host of yours is correctly resolved all the time.

**Comment by tckb** [comment]
@svartalf Ah! that was due to my slip! unbound was starting much later than unbound-telemetry. Thats why it didn't find unbound on startup. May be its a good idea to add a retry mechanism ?  perhaps can be configured as a cli argument

**Comment by svartalf** [comment]
With current implementation it connects to the `unbound` each time when you are requesting `/metrics` or `/healthcheck` endpoints:

https://github.com/svartalf/unbound-telemetry/blob/512e3e617fcab20cce6e3204e4355a30866d2c02/src/sources/control/mod.rs#L47-L57

It was implemented that way in order to mitigate this exact class of problems: there is no reason to maintain established TCP connection all the time (assuming that Prometheus will poll exporter with a few seconds interval), but if quickly shows if there are any connection issues or network configuration changes (ex., DNS name for `unbound` server is pointing to another IP address).

I don't think there is any kind of DNS cache hidden in a used tech stack, so it would be really helpful to understand what your network configuration is and it would be possible to reproduce that issue.

**Comment by tckb** [comment]
I saw that code and also makes me wonder. The exporter was earlier running as a side car container where the main unbound container was running. Since both are in the same pod, the containers was starting up together and unbound container takes few seconds for starting up. And I had the problem I described above.

I changed this behavior by moving the exporter to a separate pod and started to wait until the unbound service was started. After that, everything worked.

**Comment by svartalf** [comment]
@tckb I don't have much experience with k8s, so it is hard to say what's wrong exactly, but for me it does look like a Kubernetes-related issue, not the exporter one.
Could it be some kind of a setup problem? I'm not sure how exactly networking acts between two containers before both of them are up.

**Comment by tckb** [comment]
@svartalf  I am not sure if this is a setup issue.   Every Pod in k8s share the same networking stack and communicate with each other as if they are running on the same machine. The only thing that is not defined is the startup order. I fixed it by moving the container out to a different pod. 

Let me try to replicate the issue, out of k8s.
